my_data=[
('Adhesives (Structure)', 'Mineral Mortar Adhesive', '', '', ''),
('Aggregate', 'Aggregate', '', '', ''),
('Aggregate', 'Aggregate', 'Aggregate, Sub base, crushed once', 'kg', '0.0023'),
('Aggregate', 'Aggregate', 'Aggregate, Macadam, crushed once', 'kg', '0.0023'),
('Aggregate', 'Aggregate', 'Aggregate, Crushed Rock, crushed twice', 'kg', '0.0026'),
('Aggregate', 'Aggregate', 'Aggregate, Base Course, crushed twice', 'kg', '0.0026'),
('Aggregate', 'Aggregate', 'Aggregate, Sub base, crushed twice', 'kg', '0.0026'),
('Aggregate', 'Aggregate', 'Aggregate, Macadam, crushed twice', 'kg', '0.0026'),
('Aggregate', 'Aggregate', 'Aggregate, Railway Macadam, crushed twice', 'kg', '0.0026'),
('Aggregate', 'Aggregate', 'Aggregate, Rock Fines, crushed thrice', 'kg', '0.0026'),
('Aggregate', 'Aggregate', 'Aggregate, Crushed Rock, crushed thrice', 'kg', '0.0026'),
('Aggregate', 'Aggregate', 'Aggregate, Macadam, crushed thrice', 'kg', '0.0026'),
('Aggregate', 'Aggregate', 'Aggregate, Macadam, crushed thrice, Salt Mixed', 'kg', '0.0037'),
('Aggregate', 'Aggregate', 'Aggregate, Washed', 'kg', '0.016'),
('Aggregate', 'Aggregate', 'Aggregate, Sand,Gravel Substitute for Concrete, Feldspar Substitue for Ceramic', 'kg', '101.662'),
('Aggregate', 'Aggregate', 'Aggregate, Granite, 75mm (Diameter)', 'kg', '0.0017'),
('Aggregate', 'Aggregate', 'Aggregate, Granite, 45mm (Diameter)', 'kg', '0.00308'),
('Aggregate', 'Aggregate', 'Aggregate, Granite, 22.5mm (Diameter)', 'kg', '0.00308'),
('Aggregate', 'Aggregate', 'Aggregate, Granite, 47.5mm (Diameter)', 'kg', '0.00308'),
('Aggregate', 'Aggregate', 'Aggregate, Granite, 4mm (Diameter)', 'kg', '0.00392'),
('Aggregate', 'Aggregate', 'Aggregate, Granite, 8mm (Diameter)', 'kg', '0.00308'),
('Aggregate', 'Aggregate', 'Aggregate, Granite, 16mm (Diameter)', 'kg', '0.00316'),
('Aggregate', 'Aggregate', 'Aggregate, Granite, 2mm (Diameter)', 'kg', '0.00392'),
('Aggregate', 'Aggregate', 'Aggregate, Granite, 13.5mm (Diameter)', 'kg', '0.00392'),
('Aggregate', 'Aggregate', 'Aggregate, Granite, 19mm (Diameter)', 'kg', '0.00392'),
('Aggregate', 'Aggregate', 'Aggregate, Granite, 1mm (Diameter)', 'kg', '0.00392'),
('Aggregate', 'Aggregate', 'Aggregate, Granite, 3.5mm (Diameter)', 'kg', '0.00392'),
('Aggregate', 'Aggregate', 'Aggregate, Granite, 9.5mm (Diameter)', 'kg', '0.00392'),
('Aggregate', 'Aggregate', 'Aggregate, Granite, Cubical Shaped, 2mm (Diameter)', 'kg', '0.00392'),
('Aggregate', 'Aggregate', 'Aggregate, Granite, Cubical Shaped, 6mm (Diameter)', 'kg', '0.00392'),
('Aggregate', 'Aggregate', 'Aggregate, Granite, Cubical Shaped, 9.5mm (Diameter)', 'kg', '0.00392'),
('Aggregate', 'Aggregate', 'Aggregate, Granite, Cubical Shaped, 13.5mm (Diameter)', 'kg', '0.00392'),
('Aggregate', 'Aggregate', 'Aggregate, Blasted Rock', 'kg', '0.00163'),
('Aggregate', 'Aggregate', 'Aggregate, 125mm (Particle Size)', 'kg', '0.00198'),
('Aggregate', 'Aggregate', 'Aggregate, 75mm (Particle Size)', 'kg', '0.00215'),
('Aggregate', 'Aggregate', 'Aggregate, 45mm (Particle Size)', 'kg', '0.00215'),
('Aggregate', 'Aggregate', 'Aggregate, 16mm (Particle Size)', 'kg', '0.00202'),
('Aggregate', 'Aggregate', 'Aggregate, 47.5mm (Particle Size)', 'kg', '0.00224'),
('Aggregate', 'Aggregate', 'Aggregate, 8mm (Particle Size)', 'kg', '0.00224'),
('Aggregate', 'Aggregate', 'Aggregate, 4mm (Particle Size)', 'kg', '0.00224'),
('Aggregate', 'Aggregate', 'Aggregate, 2.5mm (Particle Size)', 'kg', '0.00224'),
('Aggregate', 'Aggregate', 'Aggregate, 19mm (Particle Size)', 'kg', '0.00225'),
('Aggregate', 'Aggregate', 'Aggregate, 24mm (Particle Size)', 'kg', '0.00225'),
('Aggregate', 'Aggregate', 'Aggregate, 9.5mm (Particle Size)', 'kg', '0.00226'),
('Aggregate', 'Aggregate', 'Aggregate, 13.5mm (Particle Size)', 'kg', '0.00226'),
('Aggregate', 'Aggregate', 'Aggregate, 12mm (Particle Size)', 'kg', '0.00226'),
('Aggregate', 'Aggregate', 'Aggregate, 1mm (Particle Size)', 'kg', '0.00227'),
('Aggregate', 'Aggregate', 'Aggregate, 3.5mm (Particle Size)', 'kg', '0.00227'),
('Aggregate', 'Aggregate', 'Aggregate, 5mm (Particle Size)', 'kg', '0.00227'),
('Aggregate', 'Aggregate', 'Aggregate, 6.5mm (Particle Size)', 'kg', '0.00227'),
('Aggregate', 'Aggregate', 'Aggregate, Washed, 47.5mm (Particle Size)', 'kg', '0.00349'),
('Aggregate', 'Aggregate', 'Aggregate, Washed, 24mm (Particle Size)', 'kg', '0.00384'),
('Bonding Agent', 'Bonding Agent', '', '', ''),
('Cement', 'Cement/concrete Additive', '', '', ''),
('Cement', 'Cement/concrete Additive', 'Cement/concrete Additive (ALI PRE GREEN)', 'kg', '0.753'),
('Cement', 'Grey Portland Cement', '', '', ''),
('Cement', 'Grey Portland Cement', 'Grey Portland Cement (High Suplhate-Resistance, Low Heat Generation), 42.5N (Compressive Strength)', 'kg', '0.925'),
('Cement', 'Grey Portland Cement', 'Grey Portland Cement (Rapid Strength Development), 52.5N (Compressive Strength)', 'kg', '0.86'),
('Cement', 'General Purpose Portland Cement', '', '', ''),
('Cement', 'General Purpose Portland Cement', 'General Purpose Portland Cement , Bagged', 'kg', '0.904'),
('Cement', 'Portland Cement', '', '', ''),
('Cement', 'Portland Cement', 'Portland Cement (Precast Concrete Products)', 'kg', '0.734'),
('Cement', 'Portland Composite Cement', '', '', ''),
('Cement', 'Portland Pozzolana Cement', '', '', ''),
('Cement', 'Portland Pozzolana Cement', 'Portland Pozzolana Cement, Plastering, Binder for Concrete and Mortar , 692 KgCO2e (GWP)', 'kg', '0.692'),
('Cement', 'Portland Pozzolana Cement', 'Portland Pozzolana Cement, Plastering, Binder for Concrete and Mortar , 862 KgCO2e (GWP)', 'kg', '0.862'),
('Cement', 'Portland Pozzolana Cement', 'Portland Pozzolana Cement, Plastering, Binder for Concrete and Mortar , 655 KgCO2e (GWP)', 'kg', '0.655'),
('Cement', 'Portland Pozzolana Cement', 'Portland Pozzolana Cement, Plastering, Binder for Concrete and Mortar , 690 KgCO2e (GWP)', 'kg', '0.69'),
('Cement', 'Portland Pozzolana Cement', 'Portland Pozzolana Cement, Plastering, Binder for Concrete and Mortar , 671 KgCO2e (GWP)', 'kg', '0.671'),
('Cement', 'Portland Pozzolana Cement', 'Portland Pozzolana Cement, Plastering, Binder for Concrete and Mortar , 702 KgCO2e (GWP)', 'kg', '0.702'),
('Cement', 'Portland Pozzolana Cement', 'Portland Pozzolana Cement, Plastering, Binder for Concrete and Mortar , 689 KgCO2e (GWP)', 'kg', '0.689'),
('Cement', 'Portland Pozzolana Cement', 'Portland Pozzolana Cement, Plastering, Binder for Concrete and Mortar , 807 KgCO2e (GWP)', 'kg', '0.807'),
('Cement', 'Portland Pozzolana Cement', 'Portland Pozzolana Cement, Plastering, Binder for Concrete and Mortar , 795 KgCO2e (GWP)', 'kg', '0.795'),
('Cement', 'Portland Pozzolana Cement', 'Portland Pozzolana Cement, Plastering, Binder for Concrete and Mortar, 807 KgCO2e (GWP)', 'kg', '0.807'),
('Cement', 'Portland Pozzolana Cement', 'Portland Pozzolana Cement, Plastering, Binder for Concrete and Mortar, 758 KgCO2e (GWP)', 'kg', '0.758'),
('Cement', 'Portland Pozzolana Cement', 'Portland Pozzolana Cement, Hydraulic structures, Masonry mortars , 992 KgCO2e (GWP)', 'kg', '0.992'),
('Cement', 'Portland Pozzolana Cement', 'Portland Pozzolana Cement, Hydraulic structures, Masonry mortars , 814 KgCO2e (GWP)', 'kg', '0.814'),
('Cement', 'Portland Pozzolana Cement', 'Portland Pozzolana Cement, Hydraulic structures, Masonry mortars , 688 KgCO2e (GWP)', 'kg', '0.688'),
('Cement', 'Portland Pozzolana Cement', 'Portland Pozzolana Cement, Hydraulic structures, Masonry mortars , 837 KgCO2e (GWP)', 'kg', '0.837'),
('Cement', 'Portland Pozzolana Cement', 'Portland Pozzolana Cement, Hydraulic structures, Masonry mortars , 732 KgCO2e (GWP)', 'kg', '0.732'),
('Cement', 'Portland Pozzolana Cement', 'Portland Pozzolana Cement, Hydraulic structures, Masonry mortars , 681 KgCO2e (GWP)', 'kg', '0.681'),
('Cement', 'Portland Pozzolana Cement', 'Portland Pozzolana Cement, Hydraulic structures, Masonry mortars , 661 KgCO2e (GWP)', 'kg', '0.661'),
('Cement', 'Portland Pozzolana Cement', 'Portland Pozzolana Cement, Hydraulic structures, Masonry mortars , 675 KgCO2e (GWP)', 'kg', '0.675'),
('Cement', 'Portland Pozzolana Cement', 'Portland Pozzolana Cement, Hydraulic structures, Masonry mortars , 686 KgCO2e (GWP)', 'kg', '0.686'),
('Cement', 'Portland Pozzolana Cement', 'Portland Pozzolana Cement, Hydraulic structures, Masonry mortars , 689 KgCO2e (GWP)', 'kg', '0.689'),
('Cement', 'Portland Pozzolana Cement', 'Portland Pozzolana Cement, Hydraulic structures, Masonry mortars , 884 KgCO2e (GWP)', 'kg', '0.884'),
('Cement', 'Portland Pozzolana Cement', 'Portland Pozzolana Cement, Hydraulic structures, Masonry mortars , 775 KgCO2e (GWP)', 'kg', '0.775'),
('Cement', 'Portland Pozzolana Cement', 'Portland Pozzolana Cement, Hydraulic structures, Masonry mortars , 111 KgCO2e (GWP)', 'kg', '0.111'),
('Cement', 'Portland Pozzolana Cement', 'Portland Pozzolana Cement, Hydraulic structures, Masonry mortars , 890 KgCO2e (GWP)', 'kg', '0.89'),
('Cement', 'Portland Pozzolana Cement', 'Portland Pozzolana Cement, Hydraulic structures, Masonry mortars , 709 KgCO2e (GWP)', 'kg', '0.709'),
('Cement', 'Portland Pozzolana Cement', 'Portland Pozzolana Cement, Hydraulic structures, Masonry mortars , 801 KgCO2e (GWP)', 'kg', '0.801'),
('Cement', 'Portland Pozzolana Cement', 'Portland Pozzolana Cement, Hydraulic structures, Masonry mortars , 848 KgCO2e (GWP)', 'kg', '0.848'),
('Cement', 'Portland Pozzolana Cement', 'Portland Pozzolana Cement, Hydraulic structures, Masonry mortars , 742 KgCO2e (GWP)', 'kg', '0.742'),
('Cement', 'Portland Pozzolana Cement', 'Portland Pozzolana Cement, Hydraulic structures, Masonry mortars , 710 KgCO2e (GWP)', 'kg', '0.71'),
('Cement', 'Portland Pozzolana Cement', 'Portland Pozzolana Cement, Hydraulic structures, Masonry mortars , 809 KgCO2e (GWP)', 'kg', '0.809'),
('Cement', 'Portland Pozzolana Cement', 'Portland Pozzolana Cement, Hydraulic structures, Masonry mortars , 692 KgCO2e (GWP)', 'kg', '0.692'),
('Cement', 'Portland Slag Cement', '', '', ''),
('Cement', 'Portland Slag Cement', 'Portland Slag Cement, Marine and off-shore, Sewer and Water treatment plants , 601 KgCO2e (GWP)', 'kg', '0.601'),
('Cement', 'Portland Slag Cement', 'Portland Slag Cement, Marine and off-shore , 665 KgCO2e (GWP)', 'kg', '0.665'),
('Cement', 'Portland Slag Cement', 'Portland Slag Cement, Marine and off-shore , 552 KgCO2e (GWP)', 'kg', '0.552'),
('Cement', 'Portland Slag Cement', 'Portland Slag Cement, Marine and off-shore , 633 KgCO2e (GWP)', 'kg', '0.633'),
('Cement', 'Portland Slag Cement', 'Portland Slag Cement, Marine and off-shore , 550 KgCO2e (GWP)', 'kg', '0.55'),
('Cement', 'Portland Slag Cement', 'Portland Slag Cement, Marine and off-shore , 930 KgCO2e (GWP)', 'kg', '0.93'),
('Cement', 'Portland Slag Cement', 'Portland Slag Cement, Marine and off-shore , 679 KgCO2e (GWP)', 'kg', '0.679'),
('Cement', 'Portland Slag Cement', 'Portland Slag Cement, Marine and off-shore , 524 KgCO2e (GWP)', 'kg', '0.524'),
('Cement', 'Portland Slag Cement', 'Portland Slag Cement, Marine and off-shore , 646 KgCO2e (GWP)', 'kg', '0.646'),
('Cement', 'Portland Slag Cement', 'Portland Slag Cement, Marine and off-shore , 467 KgCO2e (GWP)', 'kg', '0.467'),
('Cement', 'Portland Slag Cement', 'Portland Slag Cement, Marine and off-shore , 616 KgCO2e (GWP)', 'kg', '0.616'),
('Cement', 'Portland Slag Cement', 'Portland Slag Cement, Marine and off-shore , 433 KgCO2e (GWP)', 'kg', '0.433'),
('Cement', 'Portland Slag Cement', 'Portland Slag Cement, Marine and off-shore , 531 KgCO2e (GWP)', 'kg', '0.531'),
('Cement', 'Portland Slag Cement', 'Portland Slag Cement, Marine and off-shore , 439 KgCO2e (GWP)', 'kg', '0.439'),
('Cement', 'Portland Slag Cement', 'Portland Slag Cement, Marine and off-shore , 546 KgCO2e (GWP)', 'kg', '0.546'),
('Cement', 'Portland Slag Cement', 'Portland Slag Cement, 24 MPa (Compressive Strength) , 319 KgCO2e (GWP)', 'kg', '0.319'),
('Cement', 'Portland Slag Cement', 'Portland Slag Cement, 24 MPa (Compressive Strength) , 364 KgCO2e (GWP)', 'kg', '0.364'),
('Cement', 'Portland Slag Cement', 'Portland Slag Cement, 24 MPa (Compressive Strength) , 339 KgCO2e (GWP)', 'kg', '0.339'),
('Cement', 'Portland Slag Cement', 'Portland Slag Cement, 24 MPa (Compressive Strength) , 285 KgCO2e (GWP)', 'kg', '0.285'),
('Cement', 'White Portland Cement', '', '', ''),
('Concrete', 'Concrete', '', '', ''),
('Concrete', 'Precast concrete column and beam', '', '', ''),
('Concrete', 'Precast Concrete Element', '', '', ''),
('Concrete', 'Precast Concrete Element', 'Precast Concrete Element, hollow core slabs for precast flooring, pre-stressed beams', 'kg', '0.271'),
('Concrete', 'Precast reinforced solid concrete walls and floors', '', '', ''),
('Concrete', 'Ready Mix Concrete', '', '', ''),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete, 85 MPa (Compressive Strength)', 'kg', '0.174935039'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete, 25 MPa (Compressive Strength)', 'kg', '0.127826087'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (General Mix), 20 MPa', 'kg', '0.118695652'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (Fly Ash), 20 MPa', 'kg', '0.095652174'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (Ground granulated blast furnance slag), 20 MPa', 'kg', '0.074347826'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (Triple Blend), 20 MPa', 'kg', '0.066086957'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (General Mix), 25 MPa', 'kg', '0.129130435'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (Fly Ash), 25 MPa', 'kg', '0.104782609'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (Ground granulated blast furnance slag), 25 MPa', 'kg', '0.080434783'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (Triple Blend), 25 MPa', 'kg', '0.066956522'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (General Mix), 32 MPa', 'kg', '0.149130435'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (Fly Ash), 32 MPa', 'kg', '0.118695652'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (Ground granulated blast furnance slag), 32 MPa', 'kg', '0.085217391'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (Triple Blend), 32 MPa', 'kg', '0.076521739'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (General Mix), 40 MPa', 'kg', '0.176086957'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (Fly Ash), 40 MPa', 'kg', '0.142608696'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (Ground granulated blast furnance slag), 40 MPa', 'kg', '0.105652174'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (Triple Blend), 40 MPa', 'kg', '0.095217391'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (General Mix), 50 MPa', 'kg', '0.223478261'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (Fly Ash), 50 MPa', 'kg', '0.18'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (Ground granulated blast furnance slag), 50 MPa', 'kg', '0.13173913'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (Triple Blend), 50 MPa', 'kg', '0.123478261'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (Cement 7-8%), 8 MPa', 'kg', '0.071478261'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (Cement 9-10%), 8 MPa', 'kg', '0.087973913'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (Cement 9-11%), 12 MPa', 'kg', '0.09256087'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (Cement 11-13%), 12 MPa', 'kg', '0.108830435'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (Cement 10-12%), 16 MPa', 'kg', '0.103495652'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (Cement 13-14%), 16 MPa', 'kg', '0.119865217'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (Cement 12-15%), 20 MPa', 'kg', '0.120221739'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (Cement 15-17%), 20 MPa', 'kg', '0.141495652'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (Cement 13-15%), 25 MPa', 'kg', '0.126417391'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (Cement 15-17%), 25 MPa', 'kg', '0.143421739'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (Cement 16-18%), 30 MPa', 'kg', '0.148282609'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (Cement 18-20%), 35 MPa', 'kg', '0.167386957'),
('Concrete', 'Ready Mix Concrete', 'Ready Mix Concrete (Cement 20-21%), 40 MPa', 'kg', '0.178086957'),
('Concrete', 'Reinforced Solid concrete, pre-stressed, beams', '', '', ''),
('Concrete', 'Reinforced Solid Precast Concrete Product', '', '', ''),
('Concrete', 'Reinforced Solid Precast Concrete, Pre-stressed Slab', '', '', ''),
('Concrete', 'Unreinforced Autoclaved Aerated Concrete', '', '', ''),
('Concrete', 'Unreinforced Autoclaved Aerated Concrete', 'Unreinforced Autoclaved Aerated Concrete, 3.25 N/mm2 (Compressive Strength)', 'kg', '0.393700787'),
('Concrete', 'Waterproofing Slurry', '', '', ''),
('Mortar (Structure)', 'Cement-Lime Mortar', '', '', ''),
('Mortar (Structure)', 'Geo-Mortar', '', '', ''),
('Mortar (Structure)', 'Geo-Mortar', 'Geo-Mortar, Geocalce® FL Antisismico', 'kg', '0.319333333'),
('Mortar (Structure)', 'Geo-Mortar', 'Geo-Mortar, Geocalce® Multiuso', 'kg', '0.373076923'),
('Mortar (Structure)', 'Grey Mortar', '', '', ''),
('Mortar (Structure)', 'Grey Mortar', 'Grey Mortar, MAPEI Ultralite S1 Quick', 'kg', '0.802'),
('Mortar (Structure)', 'Grey Mortar', 'Grey Mortar, MAPEI Ultralite S2', 'kg', '0.939'),
('Mortar (Structure)', 'Mortar', '', '', ''),
('Mortar (Structure)', 'Mortar', 'Mortar, Waterproofing, Protection of Concrete', 'kg', '0.701'),
('Mortar (Structure)', 'Mortar', 'Mortar, Waterproofing Irregular Surface', 'kg', '0.862'),
('Mortar (Structure)', 'Mortar', 'Mortar, Waterproofing Concrete and Masonry Structure', 'kg', '0.82'),
('Mortar (Structure)', 'Mortar', 'Mortar, Rapid Waterproofing Concrete Structure', 'kg', '1.07'),
('Mortar (Structure)', 'White Mortar', '', '', ''),
('Mortar (Structure)', 'White Mortar', 'White Mortar, MAPEI Ultralite Mortar', 'kg', '1.07'),
('Mortar (Structure)', 'White Mortar', 'White Mortar, MAPEI Ultralite S1 Quick', 'kg', '0.636'),
('Mortar (Structure)', 'White Mortar', 'White Mortar, MAPEI Ultralite S2', 'kg', '0.939'),
('Slag', 'Blast-Furnace Slag', '', '', ''),
('Slag', 'Blast-Furnace Slag', 'Blast-Furnace Slag , 364 m2/kg (Fineness) , 58.5 KgCO2e (GWP)', 'kg', '0.0585'),
('Slag', 'Blast-Furnace Slag', 'Blast-Furnace Slag , 364 m2/kg (Fineness) , 55.7 KgCO2e (GWP)', 'kg', '0.0557'),
('Steel', 'Bare Spiral Welded Steel Pipe', '', '', ''),
('Steel', 'Coated Spiral Welded Steel Pipe', '', '', ''),
('Steel', 'Cold rolled reinforcing steel and electrowelded mesh', '', '', ''),
('Steel', 'Cold rolled steel sheets and coils', '', '', ''),
('Steel', 'Color coated steel sheets and coils', '', '', ''),
('Steel', 'Core Steel', '', '', ''),
('Steel', 'Galvanized Steel (coil and sheet)', '', '', ''),
('Steel', 'Galvanized structural steel flooring system', '', '', ''),
('Steel', 'Galvanized wire made from steel scrap', '', '', ''),
('Steel', 'Hot Rolled Coil', '', '', ''),
('Steel', 'Hot Rolled Steel', '', '', ''),
('Steel', 'Hot Rolled Steel Coil', '', '', ''),
('Steel', 'Hot Rolled Steel Merchant Bar', '', '', ''),
('Steel', 'Hot Rolled Steel Merchant Bar', 'Hot Rolled Steel Merchant Bar, 1200 KgCO2e (GWP)', 'kg', '1.2'),
('Steel', 'Hot Rolled Steel Plate', '', '', ''),
('Steel', 'Hot Rolled Steel Plate', 'Hot Rolled Steel Plate', 'kg', '2.71'),
('Steel', 'Hot Rolled Steel Sheets and Coils', '', '', ''),
('Steel', 'Hot Rolled Steel Structural Section', '', '', ''),
('Steel', 'Hot Rolled Steel Structural Section', 'Hot Rolled Steel Structural Section, 3200 KgCO2e (GWP)', 'kg', '3.2'),
('Steel', 'Hot-drawn reinforcing steel for concrete in bars and coils', '', '', ''),
('Steel', 'Installed hot dip galvanized steel profiles and accessories', '', '', ''),
('Steel', 'Insulated Steel Panel', '', '', ''),
('Steel', 'Insulation Panel with Steel for Roof', '', '', ''),
('Steel', 'Insulation Panel with Steel for Roof', 'Insulation Panel with Steel for Roof, 80mm (Nominal Thickness)', 'kg', '2.142857143'),
('Steel', 'Insulation Panel with Steel for Wall', '', '', ''),
('Steel', 'Insulation Panel with Steel for Wall', 'Insulation Panel with Steel for Wall, 80mm (Nominal Thickness)', 'kg', '2.154285714'),
('Steel', 'Light Gauge Steel Profile', '', '', ''),
('Steel', 'Light Gauge Steel Profile', 'Light Gauge Steel Profile for interior walls and ceilings, 0.5mm (Steel Thickness)', 'kg', '2.661'),
('Steel', 'Light Gauge Steel Profile', 'Light Gauge Steel Profile for interior walls and ceilings, 0.6mm (Steel Thickness)', 'kg', '2.643'),
('Steel', 'Light Gauge Steel Profile', 'Light Gauge Steel Profile for external walls and light weight steel beams, 0.7mm (Steel Thickness)', 'kg', '2.704'),
('Steel', 'Light Gauge Steel Profile', 'Light Gauge Steel Profile for external walls and light weight steel beams, 1mm (Steel Thickness)', 'kg', '2.659'),
('Steel', 'Light Gauge Steel Profile', 'Light Gauge Steel Profile for external walls and light weight steel beams, 1.2mm (Steel Thickness)', 'kg', '2.642'),
('Steel', 'Light Gauge Steel Profile', 'Light Gauge Steel Profile for external walls and light weight steel beams, 1.5mm (Steel Thickness)', 'kg', '2.624'),
('Steel', 'Light Gauge Steel Profile', 'Light Gauge Steel Profile for external walls and light weight steel beams, 2mm (Steel Thickness)', 'kg', '2.605'),
('Steel', 'Light Gauge Steel Profile', 'Light Gauge Steel Profile for external walls and light weight steel beams, 2.5mm (Steel Thickness)', 'kg', '2.594'),
('Steel', 'Light Gauge Steel Profile', 'Light Gauge Steel Profile for external walls and light weight steel beams, 3mm (Steel Thickness)', 'kg', '2.587'),
('Steel', 'Light Gauge Steel Profile', 'Light Gauge Steel Profile for mounting in external environments, 0.7mm (Steel Thickness)', 'kg', '2.754'),
('Steel', 'Light Gauge Steel Profile', 'Light Gauge Steel Profile for mounting in external environments, 1mm (Steel Thickness)', 'kg', '2.695'),
('Steel', 'Light Gauge Steel Profile', 'Light Gauge Steel Profile for mounting in external environments, Polyster Coated, 0.7mm (Steel Thickness)', 'kg', '2.739'),
('Steel', 'Light Gauge Steel Profile', 'Light Gauge Steel Profile for installation in external environments, 0.7mm (Steel Thickness)', 'kg', '2.785'),
('Steel', 'Light Gauge Steel Profile', 'Light Gauge Steel Profile for installation in external environments, 1mm (Steel Thickness)', 'kg', '2.715'),
('Steel', 'Low alloyed steel wire rods', '', '', ''),
('Steel', 'Low Relaxation Wire', '', '', ''),
('Steel', 'Metal coated steel sheets and coils', '', '', ''),
('Steel', 'Painted Steel (coil and sheet)', '', '', ''),
('Steel', 'Precast Steel and Concrete Pile', '', '', ''),
('Steel', 'Precast Steel and Concrete Pile', 'Precast Steel and Concrete Pile, 3091 KgCO2e (GWP)', 'kg', '0.338591302'),
('Steel', 'Pre-stressed steel rope manufactured from steel scrap', '', '', ''),
('Steel', 'Reinforcing Steel Bar', '', '', ''),
('Steel', 'Reinforcing Steel Bar', 'Reinforcing Steel Bar, 1800 KgCO2e (GWP)', 'kg', '1.8'),
('Steel', 'Reinforcing Steel Bar', 'Reinforcing Steel Bar, 25 mm (Diameter)', 'kg', '1.5'),
('Steel', 'Reinforcing Steel Bar', 'Reinforcing Steel Bar, 767 KgCO2e (GWP)', 'kg', '0.767'),
('Steel', 'Reinforcing Steel Bar', 'Reinforcing Steel Bar, 3.97 KgCO2e (GWP)', 'kg', '3.97'),
('Steel', 'Reinforcing Steel Bar', 'Reinforcing Steel Bar, 1750 KgCO2e (GWP)', 'kg', '1.75'),
('Steel', 'Reinforcing Steel Bar', 'Reinforcing Steel Bar, 0.516 KgCO2e (GWP)', 'kg', '0.516'),
('Steel', 'Reinforcing Steel Bar', 'Reinforcing Steel Bar, 605 KgCO2e (GWP)', 'kg', '0.605'),
('Steel', 'Reinforcing Steel Bar', 'Reinforcing Steel Bar, 1436 KgCO2e (GWP)', 'kg', '1.436'),
('Steel', 'Reinforcing Steel Coil', '', '', ''),
('Steel', 'Reinforcing Steel Mesh', '', '', ''),
('Steel', 'Reinforcing Steel Rod', '', '', ''),
('Steel', 'Reinforcing Steel Rod', 'Reinforcing Steel Rod, 3.78 KgCO2e (GWP)', 'kg', '3.78'),
('Steel', 'Reinforcing Steel Wire', '', '', ''),
('Steel', 'Reinforcing Steel Wire', 'Reinforcing Steel Wire, 3.9 KgCO2e (GWP)', 'kg', '3.9'),
('Steel', 'Seamless Steel Structural Tube', '', '', ''),
('Steel', 'Seamless Steel Tube', '', '', ''),
('Steel', 'Sound barrier with steel', '', '', ''),
('Steel', 'Steel Beams/Angles', '', '', ''),
('Steel', 'Steel Columns and Beams', '', '', ''),
('Steel', 'Steel Core Pile', '', '', ''),
('Steel', 'Steel Deformed Bars for Concrete Reinforcement', '', '', ''),
('Steel', 'Steel Low Relaxation Strand', '', '', ''),
('Steel', 'Steel Merchant Bar', '', '', ''),
('Steel', 'Steel Panel RIB, SSR cover, moldings or gutters', '', '', ''),
('Steel', 'Steel Pile', '', '', ''),
('Steel', 'Steel Pile', 'Steel Pile, 102.6 KgCO2e (GWP)', 'kg', '1.195804196'),
('Steel', 'Steel Pipe Piles', '', '', ''),
('Steel', 'Steel Pipe Piles', 'Steel Pipe Piles, S550J2H (Grade)', 'kg', '1.276913425'),
('Steel', 'Steel reinforcing bar manufactured from steel scrap', '', '', ''),
('Steel', 'Steel Wide Bay Square Profile', '', '', ''),
('Steel', 'Steel wide flange beam manufactured from steel scrap', '', '', ''),
('Steel', 'Steel wire rod manufactured from steel scrap', '', '', ''),
('Steel', 'Wire rod made from steel scrap', '', '', ''),
('Steel Roofing Deck', 'Steel Flooring System', '', '', ''),
('Steel Roofing Deck', 'Steel Flooring System', 'Steel Flooring System, Ternium Losacero 25, 63.5mm (Height)', 'kg', '1.729'),
('Steel Roofing Deck', 'Steel Flooring System', 'Steel Flooring System, Ternium Losacero 30, 76.2mm (Height)', 'kg', '1.721'),
]


for tup in my_data:
	if tup[0]=="Cement" or tup[0]=="Steel":
		print("Bulk Carrier")
	elif tup[0]!="Cement" and tup[0]!="Steel" and tup[0]!="":
		print("Container")
	else:
		print("")